# -*- coding: utf-8 -*-
"""
Created on Sat Aug 15 22:15:49 2026
    ^Creation date of this compilation document
Created on Thu Aug 13 01:14:57 2026
    ^Creation date of regular expression investigation document
Created on Mon Aug 10 09:33:28 2026
    ^Creation date of in-depth `zip()` function from Python standard library investigation

@author: Travis Asher
"""

# ================================================================================================
# %% Part 1: Matrix Transpositions and the `zip()` Function
# ================================================================================================
# I initiated this document as a prototyping scratchpad to map out how to transform raw dictionary 
#   structures into a standardized, parsable CSV file. 
#
# Early in this exploration (fairly soon after evaluating data serialization parameters), I 
#   realized that the # extraction output generated by the `.values()` dictionary method was shaped
#   precisely "backwards" to what I was wanting to find. 
# 
# The extraction yielded a nested `list[list[str]]` containing 3 sublists of 7 string objects. Now,
#   without loss of generality (and with only a marginal loss in notational respect), this object's
#   structure behaves analogously to a matrix with 3 rows and 7 columns.
#
# However, to stream this structure sequentially down into a physical file using `csv.writer()`, 
#   the pipeline required a sequence of rows shaped as `h` stacks of single rows by 3 columns 
#   (where `h` represents an arbitrary depth of these single row entries); this is a sort of 
#   "opposite" layout compared to what we have.
#
# Furthermore, to preserve relational data integrity, we desire that each horizontal row slice is
#   aligned such that any vertical column slice contains a string object which column index value
#   matches the structural column head defined by the dictionary's original primary keys: 
#   ["sensor_id", "raw_logs", "timestamp"]. We see that, again, this is another sort of "opposite"
#   layout compared to what we have.
# 
# What exactly is this sort of "opposite" layout that our data values have from what is required? 
#   that is the question that I sought out to answer in the following investigation. Although the 
#   portion requires the introduction of the initial dictionary raw data file to motivate it, the
#   main point of the dissertation is to dissect and study the `zip()` function.


import io
import csv
import pandas as pd

data = {
    " SENSOR_ID  ": ["  sn-101 ", " sn-102", "sn-103 ", "SN-101", "sn-104", "sn-102 ", "  sn-105 "],
    "raw_logs": [
        "ERROR|LOC:40.7128,-74.0060|VOLT:240.5",
        "WARN|LOC:39.9526,-75.1652|VOLT:missing",
        "OK|LOC:34.0522,-118.2437|VOLT:120.2",
        "ERROR|LOC:40.7128,-74.0060|VOLT:285.0",
        "OK|LOC:41.8781,-87.6298|VOLT:118.9",
        "ERROR|LOC:39.9526,-75.1652|VOLT:310.1",
        "WARN|LOC:null|VOLT:190.4"
    ],
    "timestamp": ["2026-08-01 10:00", "2026-08-01 10:05", "2026-08-01 10:10", "2026-08-01 10:15", "2026-08-01 10:20", "2026-08-01 10:25", "2026-08-01 10:30"]
}

string_buffer = io.StringIO()
writer = csv.writer(string_buffer)
writer.writerow(list(data.keys()))

# We start with our raw data list of values, list(data.values()): it is essentially a list of lists three values long, with each individual list entry itself a list of 7 values. These list values equate to the list sensor IDs for the first list item, the list of raw logs for the second list item, and the list of timestamps for the third list item. For our string_buffer, our first row will consist of the three column headers: SENSOR_ID, raw_logs, and timestamp. Obviously, if our first row is 3 items in length, the second row cannot be seven items in length. Furthermore, we desire under each respective column header to find an element of that specific data entry; this translates to desiring that for each row, the first item is a sensor ID, the second a raw log, and the third a timestamp. Essentially, if we consider list(data.values()) to be a matrix instead of a list of list, it would be a 7x3 matrix, with each row being a specific column header item. Thus, if we were to calculate the matrix transpose of this object, we would arrive at a 3x7 matrix with each column beingt a specific column header entry. For such an object, we could iterate over the rows and addend each row to our string_buffer, creating a string_buffer consisting of 3 columns of 8 rows, with the top row being the column header and each column item corresponding to the header data object above it.

# ------------------------------------------------------------------------------------------------
# %%% Side-Step: Description of the `zip()` Function for a Singleton Object Call
# ------------------------------------------------------------------------------------------------
###### NOTE: Now that I understand zip() much better than before, consider revising below****
# We will define the mapping procedure of the zip() function to a singleton object. Suppose we are passing the object X defined as a single list of n objects; that is, X = (x1,x2,...,xn). zip() takes two specific `variables` {NOTE: Not precisely "variables", but they effectively function as such for our purposes} from this input: (1) it takes the length of the object being passed to it, which in our case (a single iterable) is one: we will call this variable `L` (for "length"), so L=1; (2) it iterates across the argument passed to zip, and from every i-th iterable argument to zip(), the i-th element in each of these tuples is defined: we will call this variable `I` (for "iterator"): since the single interable object contains n sublists and, thus, iterable arguments, we have that `I=n`: this will be the number of times our zip() loop iterates. With this established, we move to the zip() loop: we will continue to fill up every 1-tuple with the requisite number of elements of the sublists of X ("iterable arguments passed to zip()") until our 1-tuple is full, and this will continue until the the entire set of values has been exhausted.
    # Thus, zip(X) produces variables L=1 and I=n, meaning that each object passed to our output list will be a L=1-tuple which we will fill with the first available sublist from within the single interable object (the "iterable arguments passed to zip()"). We will then continue this process (loop) for I=n loops, exhausting our sublists ("iterable arguments"). While zip() is iterating its internal loop, it asks "What is the next avaiable item from my argument?"
        # Loop 1: It extracts the 1st item, x1. It wraps it in a 1-tuple: (x1,)
        #       --> Output grows to ((x1,))
        # Loop 2: It extracts the 2nd item, x2. It wraps it in a 1-tuple: (x2,)
        #       --> Output grows to ((x1,),(x2,))
        # ...
        # Loop n: It extracts the nth item, xn. It wraps it in a 1-tuple: (xn,)
        #       --> Output grows to ((x1,),(x2,), ..., (xn,))
    # Hence, what we have is that zip(X) takes the single iterable containing n sublists and returns a single iterable containing n 1-tuples which each contain their own sublist within the 1-tuple.
    
# We desperately could use a concrete example. We will define A, B, and C to be list of 4 items; their contents are arbitrary, but we will define them below:
A = 4*[None]
B = 4*["at"]
C = 4*[7]
# Now, let us define X to be the list of the three above lists; that is, X is a list of sublists A, B, and C.
X = (A,B,C)
# We will now call the list X to the zip() function. What exactly are we doing here? We are feeding X, a list, directly into zip(). Because X is passed as a single iterable argument, the function treats it as a single entity, meaning our argument count variable L is equal to 1. Furthermore, because there are three sublists contained with the list X, these sublists are considered the internal elements of our single argument, meaning the zip iterator will loop exactly I=3 times to exhaust it.
# We now perform the function call: X is fed into zip(), the fact that X is passed as a single positional argument means that zip() will output 1-tuples, and zip() then begins its parallel extraction loops:
    # Loop 1: It extracts the 1st item, A. It wraps it in a 1-tuple: (A,)
    #       --> Output grows to ((A,))
    # Loop 2: It extracts the 2nd item, B. It wraps it in a 1-tuple: (B,)
    #       --> Output grows to ((A,),(B,))
    # Loop 3: It extracts the 3rd item, C. It wraps it in a 1-tuple: (C,)
    #       --> Output grows to ((A,),(B,),(C,))
# Thus, since our final loop has terminated, the output has reached its final, actual form. In order to exhaust the lazy generator, we must pass it into the list function. Hence, our final value is `z_X = ((A,),(B,),(C,))`; since we know how sublists A, B, and C are defined, we can replace the, with their actual contents. Thus, we find that z_X=list(zip(X))=(([None, None, None, None],),(['at', 'at', 'at', 'at'],),([7, 7, 7, 7],)).
z_X = list(zip(X))


# ------------------------------------------------------------------------------------------------
# %%% Side-Step 2: Description of the `zip()` Function for More General Calls
# ------------------------------------------------------------------------------------------------
# Now, at the end of all of this explanation, one might ask the following: "Why did we work through this special case of calling a singular iterable object to the zip() function?" The answer: this is actually the *wrong* way to proceed! Our intentional goal was, given a list of lists X containing n sublists (each with m elements), to find a way to obtain its transpose. Allowing for a small abuse of notation, we can equate the n sublists to n rows and the m internal objects to m columns in a matrix; our objective is to flip this structure into an m x n matrix. Is z_X the transpose of X, when equating lists, sublists, rows, and columns as above? Absolutely not! X was (equatable to) a 3x4 matrix; z_X is not even a matrix: it is a tensor. Whether or not it is a 1x3x4 Tensor (Mathematical Tensor structure) or a 3x1x4 Tensor (Python's interpretation of the shape) does not matter: it is not a matrix object. Furthermore, since the object we are desiring to obtain is equatable to a 4x3 matrix, we cannot even try to "throw away an extra axis" to have some remainder of z_X that fits the size of our matrix transpose object. What went wrong?
# What went wrong is that we are supposed to *unpack* our argument that we call to zip(). Notice that if we unpack the argument, instead of generating a stream of unary tuples containing entire sublists, the zip() iterator yields nontrivial tuples composed of individual elements. Let's take our X example above. If we were to pass an unpacked X into zip(), `zip(*X)`, what we would be doing is passing the sublists of X individually into zip() as positional arguments, meaning that we have "variable" `L=3` separate objects being passed. Next, we find what our "iterator" variable `I` is; what has changed from passing X as-is into zip()? The loop boundary has fundamentally shifted! Because we are now iterating across the elements *inside* the unpacked arguments, the loop boundary `I` is determined by the length of these arguments. Since each sublist contains 4 elements, our loop boundary variable becomes `I=4`.
# We will now proceed to zip() implementing its internal loop to generate our output values; keep in mind however that we will now be venturing one step deeper into the list of sublists than we did before. Because the outer container shell has been unpacked, our top level is no longer the sequence of sublists themselves, but a parallel stream of their internal elements. That is to say, instead of extracting a single row vector, wrapping it in a 1-tuple, and moving on, we are doing two new separate things on each iteration:
   # (1) We are extracting the i-th available object out of all sublists of objects simultaneously, and
   # (2) wrapping them collectively into a single 3-tuple. Specifically, for Loop 1, it extracts the first element from argument A, the first element from argument B, and the first element from argument C, anchoring them together into a 3-tuple: (A_1, B_1, C_1). This completed 3-tuple is then appended to our output stream.

        #{*NOTE: Technically speaking, we *were* actually doing this procedure before: it just so happened that extracting the first object, `A`, from the first argument completed the entire procedure; no further tuple space for elements existed in the full 1-tuple, and no further elements existed in the argument for the algorithm to take into the non-existent tuple space.}
# Because of the above considerations, before we proceed to the loop, let us establish what we are iterating across. "Instead of passing the container X=(A,B,C) as a single argument, unpacking evaluates the sublists A, B, and C as distinct positional arguments. While the underlying data remains unchanged, zip() now directly processes the elements within [None, None, None, None], ['at', 'at', 'at', 'at'], and [7, 7, 7, 7], respectively. We proceed with our iteration algorithm in zip():
    # Loop 1: It extracts the first element from all three arguments simultaneously (`None` from the first argument A, `'at'` from the second argument B, and `7` from the third argument C) and packs them together into a 3-tuple: `(None,'at',7)`
    #       --> Output grows to `((None,'at',7))`
    # Loop 2: It extracts the second element from all three arguments simultaneously and packs them together into a 3-tuple: `(None,'at',7)`
    #       --> Output grows to `((None,'at',7),(None,'at',7))`
    # Loop 3: It extracts the third element from all three arguments simultaneously and packs them together into a 3-tuple: `(None,'at',7)`
    #       --> Output grows to `((None,'at',7),(None,'at',7),(None,'at',7))`
    # Loop 4: It extracts the fourth element from all three arguments simultaneously and packs them together into a 3-tuple: `(None,'at',7)`
    #       --> Output grows to `((None,'at',7),(None,'at',7),(None,'at',7),(None,'at',7))`
# Thus, since our final loop has terminated, what we have above is our output for list(zip(*X)). Hence, our final value is `tX = ((None,'at',7),(None,'at',7),(None,'at',7),(None,'at',7))`.
tX = list(zip(*X))

##REASONING CHECK: So we have obtained the result of list(zip(*X)). Have we finally found the analogue for a matrix transpose of mxn matrix X to a list X of m sublists of n objects? We started with `X = (A,B,C) = ([None, None, None, None], ['at', 'at', 'at', 'at'], [7, 7, 7, 7])`, which is analagous to a 3x4 matrix. Our result from the previous calculation was `tX = list(zip(*X)) = [(None, 'at', 7), (None, 'at', 7), (None, 'at', 7), (None, 'at', 7)]`, which is analagous to a 4x3 matrix. This is promising. Let us observe the (analagous) rows of X: the first row contains all of the `None` type objects, the second row all of the string type objects, and the third all of the integer objects. Now, let us consider tX; first, notice that each row contains one of each of the above data types, all in the same column as the row they were in in the initial X matrix. This translates directly into each column containing a single data type, where the data types of each respective row `q` from X correspond to each column `q` in tX. Thus, we have achieved what we desired: tX is analagous to the matrix transpose of X.

# ================================================================================================
# %% Part 2: Regular Expressions, Lookaheads, Lookbehinds, Negated Characters, and More
# ================================================================================================
# The purpose of this document was to understand regular expressions further. In the process of 
#   doing so, I came up with various functions to enable to perform these inquiries more 
#   efficiently. These functions are documented in my "Python_General_Functions" repository with 
#   the names `qck_cut()', 'qck_search()', `qck_multisplit()', and `qck_findall()'.
#
# The following are a few of the more interesting regular expression patterns that I found.

# This especially useful regex pattern allows us to identify if a string contains exactly any letter of the flag characters, ['a', 'i', 'l', 'm', 's', 'u', 'x', 'A', 'I', 'L', 'M', 'S', 'U', 'X']; or the pattern "re.~" where `~` represents any character in the above list.
reg_flag = r"(?i)^(?:re\.)?([ailmsux])$"


# This is the evolution of the regex for extracting `status`: The alphabetic string preceding the first pipe (`|`) delimiter.
    # The first regex, reg_status1, reads as "pattern: group starts at the very beginning of the string, and contains at least one instance of an alphabetic character (but possibly more, with no upper bound); group is bounded by the occurence of the | character.
reg_status1 = r"(\A(?:[a-zA-Z])+)\|"
    # We first construct the regex pattern for status. What we desire is to obtain an expression of a sequence of alphabetic characters (of either case) that can be arbitrarily long. These expressions have the added condition that they must be preceded by the start of the string and succeeded by the '|' character.
regex_status2 = r"^([a-zA-Z]+)\|"


# This is the evolution of the regex for extracting `latitude`: The numeric coordinate text isolated immediately following the `LOC:` flag.
    # These were early attempts at making regex patterns to parse "raw_logs" from above. Although they had a good idea of how to handle decimal patterns, they weren't specialized enough.
reg_latitude0 = r":((?:\d+\.\d+)+)"
    # The second regex, reg_latitude1, reads as "pattern: a colon bounds the group to the left; the group then consists of either one single chain of {at least one decimal digit (but possibly more w/ no upper bound) followed by a single period followed by at least one more decimal digit (but possibly more w/ no upper bound)} or any number (including none) of alphabetic characters."
reg_latitude1 = r":((?:(?:\d+\.\d+))|(?:[a-zA-Z]*))"
    # We next work on the regex pattern for latitude. What we desire is to obtain an expression of a sequence of decimal digits of any (nonzero) length followed by a single period ("decimal point") followed by any (nonzero) number of more decimal digits, with an optional minus ("negative sign") in front with the look-ahead condition requiring the presence of a comma, or alternatively, an expression of a sequence of alphabetic characters (of either case) that can be arbitrarily long with the look-ahead condition requiring the presence of a | symbol. These expressions have the added condition that they must be preceded by "LOC:" in the string.
        # NOTE: The optional negative sign and look-ahead are NOT required for this code to work, but they do give the regex pattern more general power
regex_lat_looks = r"LOC:((?:-?\d+\.\d+(?=,))|(?:[a-zA-Z]+(?=\|)))"
# ...HOWEVER, Polars does not support lookahead or lookbehind regex! So, we try to get this general power without them. We come up with an amazing use of a negated character class: using the construction `[^~]`, we are setting up a statement that says "match exactly one character, so long as it is NOT any input that follows. So, for our case, we want to anchor ourselves on the left with "LOC:", as before, and what we want is to extract whatever comes next before we either hit the `comma` after the latitude that separates it from the longitude or before the `pipe` that separates the error/missing value from "VOLT" that comes after it. Our negated character class is hence `[^,|]`, which translates to "match any single character, provided it is neither a comma nor a pipe." To get all of the characters we desire, we will use `+` after it to indicate "at least one occurence up to a boundless number of occurences. Combining this with our anchor, we end up building the statement "Start after `LOC:` and begin to capture each successive character that is neither a comma nor a pipe. Once you encounter a comma or a pipe, so long as you've captured a single character, the `+` quantifier is satisfied. Thus, return the group of characters captured." This is represented in regex below.
        # NOTE: So why didn't the pipe need to be escaped this time? In the regex lookahead, we had
        # to make use of the backslash `\` in order to properly match string chracters. Generally
        # (outside of these brackets), the pipe symbol `|` means "Alternation" (Logical OR) and is 
        # a *structural command character*. This means that if you want it to match a literal line
        # separator within text, you must escape it using the backslash `\|`. However, when within
        # brackets, alternation doesn't exist: a chracter class is *already* an implied list of
        # literal choices. Thus, within the brackets, the parsing engine treats the pipe character
        # `|` as a literal pipe character.
regex_lat_neg = r"LOC:([^,|]+)"

# This is the evolution of the regex for extracting `voltage`: The floating-point decimal trailing the `VOLT:` flag.
    # These were early attempts at making regex patterns to parse "raw_logs" from above. Although they had a good idea of how to handle decimal patterns, they weren't specialized enough.
reg_voltage0 = r"VOLT:(\d+\.\d+)"
    # The third regex, reg_voltage1, reads as "pattern: group is bordered to the left by "VOLT:"; the group then consists of possibly a single (or no) chain of {at least one decimal digit (but possibly more w/ no upper bound) followed by a single period followed by at least one more decimal digit (but possibly more w/ no upper bound)} or any number (including none) of alphabetic characters. The group is then bounded on the right by the end of the string."
reg_voltage1 = r"VOLT:((?:\d+\.\d+)?|(?:[a-zA-Z]*))\Z"
    # Our final regex pattern is for voltage. What we desire is to obtain an expression of a sequence of decimal digits of any (nonzero) length followed by a single period ("decimal point") followed by any (nonzero) number of more decimal digits, or alternatively, an expression of a sequence of alphabetic characters (of either case) that can be arbitrarily long. These expressions have the added condition that the must be preceded by "VOLT:" and succeeded by the end of the string.
regex_volt2 = r"VOLT:((?:\d+\.\d+)|[a-zA-Z]+)$"
              

